# Generated by Django 4.2 on 2023-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anecdot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('like_count', models.IntegerField(default='0')),
                ('category', models.CharField(choices=[('Family', 'FAMILY'), ('Army', 'ARMY'), ('Other', 'OTHER')], default='Other', max_length=10)),
            ],
        ),
    ]
